
text = [
    #Animal
"El león es conocido como el rey de la selva",
"Las ballenas son los mamíferos más grandes del planeta",
"Las abejas son esenciales para la polinización de muchas plantas",
"Los elefantes tienen una memoria increíblemente desarrollada",
"Los gatos son cazadores naturales, incluso en su vida doméstica",
"Los perros son considerados los mejores amigos del hombre",
"Las tortugas pueden vivir más de 100 años",
"Los caballos han sido compañeros del ser humano desde tiempos antiguos",
"Los delfines son animales altamente inteligentes",
"Las águilas tienen una vista excepcionalmente aguda",
"Los osos polares dependen del hielo marino para cazar",
"Los pingüinos son aves que no pueden volar pero son excelentes nadadores",
"Los tigres son los felinos más grandes del mundo",
"Las jirafas tienen el cuello más largo de todos los animales terrestres",
"Los camaleones son famosos por su capacidad de cambiar de color",
"Las cebras tienen rayas únicas que las distinguen entre sí",
"Los lobos son animales sociales que viven en manadas",
"Los canguros usan sus colas para equilibrarse mientras saltan",
"Las mariposas pasan por un ciclo de vida fascinante, desde orugas hasta adultos",
"Las serpientes mudan su piel varias veces al año",
"Los osos hibernan durante el invierno para conservar energía",
"Las ranas pueden vivir tanto en el agua como en la tierra",
"Los murciélagos son los únicos mamíferos que pueden volar",
"Los pavos reales son conocidos por sus deslumbrantes plumas",
"Los gatos tienen una agilidad extraordinaria",
"Las nutrias marinas usan herramientas para abrir mariscos",
"Los pingüinos emperadores son los más altos de su especie",
"Los rinocerontes tienen una piel gruesa que los protege de los depredadores",
"Las ballenas jorobadas son conocidas por sus saltos fuera del agua",
"Los tiburones tienen una increíble capacidad para detectar sangre en el agua",
"Las tortugas marinas regresan a la playa donde nacieron para poner sus huevos",
"Los elefantes se comunican a través de sonidos que los humanos no pueden escuchar",
"Las cebras se mueven en manadas para protegerse de los depredadores",
"Los tigres tienen un rugido que se puede escuchar a kilómetros de distancia",
"Los delfines tienen un sistema de ecolocalización para moverse y cazar",
"Las águilas calvas son el símbolo nacional de Estados Unidos",
"Los lobos grises tienen un complejo sistema de comunicación",
"Los pandas gigantes son una especie en peligro de extinción",
"Las iguanas pueden regenerar su cola si la pierden",
"Los cangrejos pueden caminar de lado debido a la estructura de sus patas",
"Las mantarrayas tienen una envergadura impresionante",
"Los zorros son conocidos por su astucia y habilidad para cazar",
"Los perezosos pasan la mayor parte de su vida en los árboles",
"Las avestruces son las aves más grandes del mundo",
"Los elefantes africanos tienen orejas más grandes que los asiáticos",
"Las serpientes venenosas utilizan su veneno para cazar y defenderse",
"Los leones cazan en manadas para atrapar presas más grandes",
"Las cebras tienen un excelente sentido de la vista y el oído",
"Los delfines forman grupos sociales muy unidos",
"Las mariposas monarca migran miles de kilómetros cada año",
"Los pingüinos usan sus alas como aletas para nadar",
"Los lobos tienen un fuerte instinto de protección hacia su manada",
"Las ranas venenosas tienen colores brillantes como advertencia",
"Los camellos pueden sobrevivir sin agua durante largos periodos",
"Las tortugas terrestres tienen un caparazón resistente",
"Los elefantes africanos son los animales terrestres más grandes",
"Las águilas construyen nidos en lo alto de los árboles o acantilados",
"Los zorros del desierto tienen orejas grandes para disipar el calor",
"Los búhos pueden girar su cabeza casi completamente alrededor",
"Las cobras levantan la parte frontal de su cuerpo como advertencia",
"Los gorilas son primates que viven en grupos familiares",
# Economía
"La inflación reduce el poder adquisitivo de los consumidores",
"El PIB es una medida clave de la salud económica de un país",
"El desempleo es un indicador crítico del bienestar económico",
"Los bancos centrales utilizan tasas de interés para controlar la inflación",
"Las exportaciones son una fuente importante de ingresos para un país",
"El mercado de valores refleja la confianza de los inversores en la economía",
"El comercio internacional fomenta la especialización y la eficiencia",
"La recesión económica puede llevar a una disminución en el gasto del consumidor",
"El crecimiento económico sostenible es clave para el desarrollo a largo plazo",
"El déficit fiscal ocurre cuando los gastos del gobierno superan sus ingresos",
"La deuda pública es el total de préstamos que un gobierno ha contraído",
"El tipo de cambio afecta las importaciones y exportaciones de un país",
"La globalización ha aumentado la interdependencia económica entre las naciones",
"El consumo es una de las principales fuerzas impulsoras de la economía",
"Los aranceles son impuestos sobre las importaciones que pueden afectar el comercio",
"La política monetaria es una herramienta utilizada para controlar la inflación",
"El ahorro es esencial para la inversión y el crecimiento económico",
"Las remesas son una fuente importante de ingresos para muchos países en desarrollo",
"El libre comercio permite la circulación sin restricciones de bienes y servicios",
"El gasto público en infraestructura puede estimular el crecimiento económico",
"El mercado laboral es un componente clave de la economía",
"El precio del petróleo tiene un impacto significativo en la economía global",
"La inversión extranjera directa es crucial para el desarrollo económico de muchos países",
"El consumo privado es la mayor parte del gasto total en muchas economías",
"Los subsidios gubernamentales pueden distorsionar el mercado",
"El aumento de los impuestos puede reducir el consumo y la inversión",
"El crédito es fundamental para el funcionamiento de las economías modernas",
"El desarrollo económico se mide por el aumento del bienestar general",
"La productividad es clave para mejorar el nivel de vida",
"La economía de escala se refiere a la reducción de costos al aumentar la producción",
"El salario mínimo es un tema de debate en muchas economías",
"La oferta y la demanda determinan los precios en una economía de mercado",
"La innovación tecnológica es un motor importante del crecimiento económico",
"El ciclo económico describe las fluctuaciones en la actividad económica",
"La inflación moderada es vista como un signo de una economía saludable",
"El capital humano se refiere a las habilidades y conocimientos de la fuerza laboral",
"El comercio electrónico ha transformado la forma en que las personas compran y venden",
"El proteccionismo económico busca proteger a las industrias locales de la competencia extranjera",
"Las políticas fiscales incluyen el uso de impuestos y gastos públicos para influir en la economía",
"El comercio justo busca asegurar que los productores reciban un precio justo por sus productos",
"El crecimiento económico inclusivo es aquel que beneficia a todas las capas de la sociedad",
"El gasto en educación es una inversión en el futuro económico de un país",
"La desigualdad económica puede ser un obstáculo para el desarrollo sostenible",
"El mercado negro se refiere a la economía informal que opera fuera de la ley",
"La competitividad económica se mide por la capacidad de un país para atraer inversiones",
"El ahorro y la inversión son fundamentales para el crecimiento económico",
"La inflación alta puede erosionar los ahorros de los ciudadanos",
"El mercado de trabajo afecta directamente el nivel de vida de la población",
"El déficit comercial ocurre cuando un país importa más de lo que exporta",
"El capital financiero incluye recursos como acciones y bonos",
"El consumo responsable es clave para la sostenibilidad económica",
"El gasto militar es una parte significativa del presupuesto en muchos países",
"Las fluctuaciones en el tipo de cambio pueden afectar las economías emergentes",
"El microcrédito es una herramienta para ayudar a las personas en economías en desarrollo",
"El crecimiento económico puede ser impulsado por la innovación y el emprendimiento",
"La economía circular busca reducir el desperdicio y promover el reciclaje",
"El emprendimiento es clave para la creación de empleo y el crecimiento económico",
"El gasto en salud es esencial para mantener una fuerza laboral productiva",
"El mercado inmobiliario es un indicador importante de la salud económica",
"La planificación financiera es crucial para la estabilidad económica a largo plazo",
"El turismo es una fuente importante de ingresos para muchos países",
# Tecnología
"El avance de la inteligencia artificial está transformando múltiples industrias.", 
"Los algoritmos de machine learning permiten predecir comportamientos futuros.", 
"El blockchain ofrece una forma segura y transparente de realizar transacciones.", 
"Las criptomonedas están cambiando el panorama financiero global.", 
"La realidad aumentada está revolucionando la manera en que interactuamos con el mundo.", 
"La realidad virtual permite crear experiencias inmersivas para el usuario.", 
"El Internet de las Cosas conecta dispositivos en todo el mundo para crear redes inteligentes.", 
"El big data es fundamental para la toma de decisiones basadas en datos.", 
"La computación en la nube ofrece escalabilidad y flexibilidad a las empresas.", 
"La ciberseguridad es crucial para proteger la información sensible de las organizaciones.", 
"Las redes neuronales son la base de muchos sistemas de inteligencia artificial.", 
"Los algoritmos son esenciales para resolver problemas complejos en informática.", 
"La programación es una habilidad fundamental en la era digital.", 
"El desarrollo web es clave para crear aplicaciones y servicios en línea.", 
"El desarrollo de software requiere un enfoque sistemático y estructurado.", 
"Los dispositivos móviles han transformado la manera en que nos comunicamos y trabajamos.", 
"Las aplicaciones móviles están redefiniendo la interacción entre usuarios y servicios.", 
"La gestión de datos es esencial para el análisis y la toma de decisiones.", 
"El comercio electrónico facilita la compra y venta de productos en todo el mundo.", 
"La robótica está avanzando rápidamente, impactando la manufactura y otros sectores.", 
"La automatización de procesos mejora la eficiencia y reduce los errores humanos.", 
"Los sistemas operativos son el corazón de cualquier dispositivo informático.", 
"La interfaz de usuario debe ser intuitiva y fácil de usar para garantizar una buena experiencia.", 
"La experiencia de usuario es crucial para la satisfacción y retención de clientes.", 
"La tecnología wearable permite monitorear la salud y el bienestar en tiempo real.", 
"La impresión 3D está revolucionando la manufactura y el diseño de productos.", 
"La gestión de proyectos tecnológicos requiere habilidades tanto técnicas como de liderazgo.", 
"La tecnología emergente abre nuevas posibilidades y retos en el mercado.", 
"La innovación tecnológica es un motor clave para el crecimiento económico.", 
"El IoT está creando nuevas oportunidades para la automatización y la conectividad.", 
"El análisis de big data permite obtener insights valiosos a partir de grandes volúmenes de información.", 
"La realidad mixta combina elementos físicos y digitales para crear nuevas experiencias.", 
"La computación cuántica promete revolucionar la resolución de problemas complejos.", 
"La seguridad informática es vital para proteger contra amenazas cibernéticas.", 
"La programación orientada a objetos es un paradigma fundamental en el desarrollo de software.", 
"La ingeniería de software abarca el diseño, desarrollo y mantenimiento de sistemas complejos.", 
"La integración de sistemas asegura que diferentes tecnologías funcionen juntas de manera eficiente.", 
"La computación distribuida permite procesar datos en múltiples ubicaciones simultáneamente.", 
"Las redes sociales han cambiado la manera en que nos comunicamos y compartimos información.", 
"Las plataformas digitales facilitan el acceso a servicios y contenido en línea.", 
"La transformación digital es esencial para que las empresas se mantengan competitivas.", 
"La tecnología disruptiva altera mercados establecidos y crea nuevas oportunidades.", 
"El desarrollo ágil permite la entrega rápida y eficiente de proyectos de software.", 
"Los sistemas de información gestionan datos y procesos clave para las organizaciones.", 
"La estrategia digital es fundamental para el éxito en el entorno empresarial moderno.", 
"La gestión de proyectos tecnológicos implica la coordinación de recursos y plazos.", 
"La arquitectura de software define la estructura y comportamiento de un sistema.", 
"La tecnología móvil continúa evolucionando con avances en hardware y software.", 
"Las nubes híbridas combinan lo mejor de la nube pública y privada para ofrecer flexibilidad.", 
"La integración continua facilita el desarrollo y la entrega de software de alta calidad.", 
"La automatización de procesos ayuda a reducir costos y mejorar la eficiencia.", 
"La tecnología verde busca minimizar el impacto ambiental de la innovación.", 
"La biometría se utiliza para identificar a las personas a través de características físicas únicas.", 
"La tecnología educativa está transformando la manera en que aprendemos y enseñamos.", 
"La ingeniería de datos es esencial para manejar grandes volúmenes de información.", 
"La tecnología financiera está cambiando la manera en que gestionamos nuestras finanzas.", 
"La realidad extendida incluye AR, VR y MR para crear experiencias inmersivas y enriquecidas.",
"La computación en el borde permite procesar datos cerca de su origen para reducir la latencia.",
# Deportes
"El fútbol es el deporte más popular del mundo.", 
"El baloncesto requiere velocidad, agilidad y precisión.", 
"El atletismo es la base de muchas disciplinas deportivas.", 
"El tenis combina habilidad técnica y resistencia física.", 
"El ciclismo es un deporte de resistencia que exige gran fortaleza mental.", 
"El boxeo es un deporte de contacto que requiere tanto fuerza como estrategia.", 
"El rugby es conocido por su intensidad y espíritu de equipo.", 
"La natación es un deporte completo que ejercita todos los músculos del cuerpo.", 
"El béisbol es conocido como el pasatiempo nacional en Estados Unidos.", 
"El hockey sobre hielo es un deporte rápido y dinámico.", 
"El golf requiere precisión y control mental en cada golpe.", 
"El voleibol es un deporte de equipo que demanda coordinación y rapidez.", 
"El esquí es un deporte que combina velocidad y técnica en la nieve.", 
"El surf es un deporte acuático que requiere equilibrio y destreza.", 
"El karate es una disciplina marcial que se enfoca en la defensa personal.", 
"El judo es un deporte de combate que promueve el respeto y la disciplina.", 
"El automovilismo es un deporte que combina velocidad y tecnología avanzada.", 
"El motociclismo es una modalidad extrema que desafía la habilidad y el coraje.", 
"El balonmano es un deporte de equipo que combina fuerza y agilidad.", 
"El triatlón es una prueba de resistencia que combina natación, ciclismo y carrera.", 
"El tenis de mesa requiere reflejos rápidos y precisión milimétrica.", 
"El esquí acuático combina la emoción del esquí con la velocidad del agua.", 
"El paracaidismo es un deporte extremo que ofrece una descarga de adrenalina.", 
"El snowboard es una modalidad que mezcla esquí y técnicas de skate en la nieve.", 
"El tiro con arco requiere concentración, precisión y control del cuerpo.", 
"El críquet es un deporte que combina estrategia, resistencia y habilidad técnica.", 
"El bádminton es un deporte de raqueta que demanda velocidad y reflejos rápidos.", 
"El ajedrez es considerado un deporte mental que ejercita la mente.", 
"El levantamiento de pesas es un deporte que pone a prueba la fuerza física y mental.", 
"El patinaje artístico es una disciplina que mezcla deporte con arte sobre hielo.", 
"El kárate es una disciplina que promueve la autodisciplina y el respeto.", 
"El fútbol americano es conocido por su intensidad y estrategia en el campo.", 
"El béisbol es un deporte de precisión y estrategia en cada jugada.", 
"El atletismo incluye una variedad de disciplinas como carreras, saltos y lanzamientos.", 
"El esquí alpino es un deporte que desafía la técnica y la velocidad en la montaña.", 
"El baloncesto se juega en equipo, donde la coordinación y la táctica son clave.", 
"El fútbol requiere técnica, resistencia y trabajo en equipo.", 
"El hockey sobre césped es un deporte rápido que demanda coordinación y agilidad.", 
"El triatlón combina tres disciplinas: natación, ciclismo y carrera.", 
"El rugby es un deporte de contacto que exige fuerza y espíritu de equipo.", 
"El ciclismo es un deporte de resistencia que se practica en carretera o montaña.", 
"El patinaje de velocidad es una disciplina que combina técnica y velocidad en el hielo.", 
"El voleibol de playa es una variante del voleibol que se juega en la arena.", 
"El judo es una disciplina que enseña autocontrol y respeto por el adversario.", 
"El automovilismo es un deporte donde la velocidad y la precisión son fundamentales.", 
"El motocross es una modalidad extrema del motociclismo en terreno accidentado.", 
"El boxeo es un deporte que combina fuerza física y agilidad mental.", 
"El surf es un deporte acuático que se practica sobre las olas del mar.", 
"El balonmano es un deporte que exige rapidez y coordinación en equipo.", 
"El golf es un deporte que se juega en amplios campos al aire libre.", 
"El ciclismo de montaña es una modalidad que combina resistencia y técnica en terrenos irregulares.", 
"El tenis es un deporte de raqueta que se juega en diferentes superficies.", 
"El atletismo se compone de diversas pruebas de pista y campo.", 
"El tiro con arco es una disciplina que exige precisión y control mental.", 
"El kárate es un arte marcial que promueve la defensa personal y la autodisciplina.", 
"El béisbol es un deporte estratégico que se juega con bate y pelota.", 
"El fútbol es una pasión que une a millones de personas en todo el mundo.", 
"El tenis de mesa es un deporte rápido que requiere reflejos y coordinación.", 
"El ajedrez es un deporte intelectual que pone a prueba la estrategia y el cálculo.",
"El levantamiento de pesas es un deporte que exige fuerza y técnica en cada levantamiento."

]
categories = ['animal'] * 60 + ['economía'] * 60 + ['tecnología'] * 60 + ['deportes'] * 60

data = {
    'text': text,
    'category': categories
}

print(len(data['text']))





'''
'category': [
        'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes'
    ]
'''
