data = {
    'text': [
        # Animal
        "El ágil zorro se deslizó entre los arbustos",
        "La tortuga avanzó lentamente hacia el mar",
        "El gorila se golpeó el pecho con fuerza",
        "Las mariposas revolotean en el jardín",
        "El búho ululaba en lo alto del árbol",
        "Las serpientes se esconden entre las rocas",
        "El delfín saltó fuera del agua",
        "Los caballos galopan en el campo abierto",
        "El lobo aullaba a la luna llena",
        "El camaleón cambia de color para camuflarse",
        "Los elefantes marchan en manada por la sabana",
        "El águila planea majestuosamente en el cielo",
        "La cebra se mezcla con las rayas de la hierba",
        "El puma acecha sigilosamente entre los arbustos",
        "Las focas juegan en las frías aguas del océano",
        "El león ruge con fuerza para marcar su territorio",
        "Las ranas croan al anochecer en el estanque",
        "El jaguar se desliza en la selva con agilidad",
        "El pato nada tranquilamente en el lago",
        "La tortuga de Galápagos es conocida por su longevidad",
        "El lince observa desde su escondite en el bosque",
        "Las golondrinas construyen sus nidos en los aleros",
        "El ciervo brama durante la temporada de apareamiento",
        "El pinguino desliza sobre el hielo en su hábitat polar",
        "Las avispas construyen sus colmenas en los árboles",
        "El tucán muestra su colorido pico en la selva",
        "El corzo se mueve ágilmente entre los árboles",
        "La medusa flota lentamente en el mar",
        "El loro repite palabras que escucha en su entorno",
        "Las nutrias juegan en las corrientes de agua dulce",
        "El pavo real exhibe su espléndida cola durante el cortejo",
        "El koala se aferra a las ramas de un eucalipto",
        "Las abejas recolectan néctar de las flores",
        "El zorrillo emite un fuerte olor para defenderse",
        "Las ardillas guardan nueces para el invierno",
        "El rinoceronte se desplaza con paso pesado en la llanura",
        "La serpiente de cascabel hace sonar su cola para advertir",
        "El canguro salta grandes distancias en su hábitat australiano",
        "El pingüino emperador cría a sus polluelos en la Antártida",
        "Las hienas se agrupan para cazar en la sabana",
        "El alce camina majestuosamente por los bosques del norte",
        "La cabra montés se mueve hábilmente por las rocas",
        "El búfalo africano vive en grandes manadas en la sabana",
        "El aguilucho busca presas desde las alturas",
        "Las golondrinas migran grandes distancias en busca de clima cálido",
        "El pelícano pesca en las aguas costeras",
        "El tiburón nada en las profundidades del océano",
        "El gato doméstico acecha sigilosamente a su presa",
        "Las ratas de campo se esconden en sus madrigueras",
        "El puma observa desde lo alto de una roca",
        "La nutria marina usa herramientas para abrir conchas",
        "El armadillo se enrolla para protegerse de los depredadores",
        "El jabalí huele en busca de alimento en el bosque",
        "La mantis religiosa se camufla entre las hojas verdes",
        "El caballo salvaje recorre vastas llanuras",
        "El lobo gris es conocido por su comportamiento social",
        "Las mariposas monarca migran desde América del Norte",
        "El ganso migratorio vuela en formaciones en V",
        "El tiburón blanco es uno de los depredadores marinos más temidos",
        "El tiburón blanco es uno de los depredadores marinos más temidos",
        "El tiburón blanco es uno de los depredadores marinos más temidos",



        # Economía
        "El mercado inmobiliario está en auge",
        "Los ingresos fiscales han aumentado este trimestre",
        "Las exportaciones de bienes agrícolas han crecido",
        "El sector tecnológico está impulsando la economía",
        "Los inversores están preocupados por la volatilidad",
        "La deuda pública ha alcanzado un nuevo récord",
        "El comercio internacional se ha desacelerado",
        "Las empresas están optimizando sus cadenas de suministro",
        "La industria automotriz está experimentando cambios",
        "Las políticas monetarias afectan a las pequeñas empresas",
        "El dinero cada vez vale menos que antes",
        "Las startups están buscando capital de riesgo",
        "La inflación ha afectado el poder adquisitivo de los consumidores",
        "El crecimiento económico ha sido moderado en el último año",
        "Las tasas de interés han sido ajustadas por el banco central",
        "La bolsa de valores muestra signos de inestabilidad",
        "El precio del petróleo ha fluctuado considerablemente",
        "Las criptomonedas están ganando aceptación en el mercado",
        "Las políticas fiscales están siendo revisadas por el gobierno",
        "La inversión en infraestructura es una prioridad nacional",
        "El desempleo ha disminuido debido a la recuperación económica",
        "Las exportaciones han sido impulsadas por acuerdos comerciales",
        "El mercado laboral está experimentando cambios estructurales",
        "La economía digital está transformando los negocios tradicionales",
        "El presupuesto nacional ha sido ajustado para el próximo año",
        "La sostenibilidad se ha convertido en un foco de inversión",
        "Las tarifas de importación han sido modificadas recientemente",
        "El costo de vida ha aumentado en las principales ciudades",
        "La política monetaria está dirigida a controlar la inflación",
        "Las fusiones y adquisiciones están en aumento en el sector corporativo",
        "La economía global está influenciada por las tensiones comerciales",
        "La recesión ha llevado a una disminución en el consumo",
        "El mercado de valores está viendo una mayor volatilidad",
        "Las políticas gubernamentales están afectando el crecimiento empresarial",
        "La inversión extranjera está buscando mercados emergentes",
        "El índice de precios al consumidor ha aumentado",
        "Las empresas están adoptando nuevas tecnologías para mejorar la eficiencia",
        "El gasto público está siendo reevaluado para optimizar recursos",
        "La transición energética está impactando el sector energético",
        "El aumento de los costos laborales afecta a las pequeñas empresas",
        "Las proyecciones económicas están siendo revisadas a la baja",
        "La innovación en finanzas está cambiando la forma en que se realizan las transacciones",
        "La recuperación económica está siendo impulsada por el sector servicios",
        "El mercado de bienes raíces está viendo una desaceleración",
        "Las tasas de interés están en niveles históricamente bajos",
        "El crecimiento del comercio electrónico está transformando el retail",
        "La deuda corporativa ha aumentado debido a la expansión de las empresas",
        "Las políticas de austeridad están siendo debatidas en el parlamento",
        "La estabilidad económica es fundamental para la inversión extranjera",
        "El crecimiento del PIB está siendo impulsado por la tecnología",
        "La regulación financiera está siendo revisada para mayor transparencia",
        "Las tendencias en el mercado laboral están cambiando con la digitalización",
        "La innovación en productos financieros está creando nuevas oportunidades",
        "El acceso a crédito ha mejorado para las pequeñas empresas",
        "La economía verde está ganando relevancia en las políticas públicas",
        "El costo de los insumos está afectando la rentabilidad de las empresas",
        "La competitividad en el mercado está impulsando la innovación",
        "Las políticas comerciales están siendo renegociadas con socios internacionales",
        "Las políticas comerciales están siendo renegociadas con socios internacionales",
        "Las políticas comerciales están siendo renegociadas con socios internacionales",
        "Las políticas comerciales están siendo renegociadas con socios internacionales",

        # Tecnología
        "El coche autónomo se ha convertido en una realidad",
        "La criptomoneda sigue ganando popularidad",
        "El software de reconocimiento facial es controvertido",
        "Los dispositivos de IoT están interconectados",
        "La ciberseguridad es crucial en la era digital",
        "El aprendizaje automático mejora con datos masivos",
        "El metaverso ofrece nuevas oportunidades sociales",
        "La computación cuántica promete revolucionar la ciencia",
        "Las impresoras 3D están cambiando la fabricación",
        "La tecnología blockchain asegura las transacciones",
        "El 5G está transformando las telecomunicaciones",
        "La realidad aumentada está ganando terreno en el entretenimiento",
        "La inteligencia artificial está mejorando la automatización",
        "El desarrollo de baterías más eficientes es una prioridad tecnológica",
        "La tecnología de voz está mejorando la interacción con dispositivos",
        "Los vehículos eléctricos están en aumento en el mercado",
        "La telemedicina está revolucionando el cuidado de la salud",
        "La biotecnología está avanzando en la investigación médica",
        "La automatización del hogar está facilitando la vida diaria",
        "Los algoritmos de recomendación están personalizando la experiencia del usuario",
        "La robótica está mejorando la precisión en la industria",
        "La realidad virtual está transformando la educación y el entrenamiento",
        "Los sistemas de gestión de datos están optimizando las operaciones empresariales",
        "La evolución del software está permitiendo nuevas aplicaciones",
        "La tecnología de sensores está mejorando la vigilancia y el monitoreo",
        "La conectividad inalámbrica está expandiendo el acceso a internet",
        "El análisis de datos grandes está impulsando la toma de decisiones",
        "La integración de la inteligencia artificial en la atención al cliente está creciendo",
        "El diseño de interfaces está mejorando la usabilidad de los sistemas",
        "La tecnología de reconocimiento de patrones está avanzando en la seguridad",
        "La investigación en nanotecnología promete innovaciones en diversos campos",
        "Los dispositivos portátiles están monitorizando la salud en tiempo real",
        "La integración de sistemas es clave para la eficiencia en empresas",
        "La tecnología de nube está facilitando la colaboración remota",
        "El uso de drones está expandiéndose en diversas industrias",
        "La evolución de los algoritmos está mejorando la precisión en las predicciones",
        "El desarrollo de nuevas tecnologías está impulsando la economía digital",
        "La interacción entre humanos y máquinas está mejorando con el tiempo",
        "El acceso a la tecnología está mejorando la educación en regiones remotas",
        "La investigación en inteligencia artificial está enfocada en la ética y la seguridad",
        "La tecnología de reconocimiento de voz está haciendo los dispositivos más accesibles",
        "El uso de big data está optimizando las estrategias de marketing",
        "La integración de tecnologías emergentes está creando nuevas oportunidades de negocio",
        "La evolución de la tecnología móvil está transformando la comunicación",
        "El desarrollo de tecnologías sustentables está reduciendo el impacto ambiental",
        "La realidad extendida está creando nuevas formas de interacción",
        "La tecnología de red está mejorando la conectividad global",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",
        "La evolución en la tecnología de almacenamiento está facilitando el manejo de datos",

        # Deportes
        "El fútbol es el deporte más popular en el mundo",
        "La Fórmula 1 es conocida por su alta velocidad",
        "El baloncesto requiere habilidades de coordinación",
        "El tenis se juega en diferentes superficies",
        "La natación es un excelente ejercicio cardiovascular",
        "El ciclismo puede ser recreativo o competitivo",
        "El béisbol es famoso en América del Norte",
        "El rugby se juega con un balón ovalado",
        "El voleibol puede jugarse en la playa o en interior",
        "El golf es conocido por sus campos extensos",
        "La gimnasia exige flexibilidad y fuerza",
        "El esquí es popular en regiones nevadas",
        "El hockey sobre hielo se juega en una pista cubierta",
        "El atletismo incluye carreras y saltos",
        "El boxeo es un deporte de contacto intenso",
        "La equitación es practicada en diferentes disciplinas",
        "El judo es un arte marcial de origen japonés",
        "El surf se practica en el mar con una tabla",
        "El karate es conocido por sus técnicas de golpeo",
        "La lucha libre se celebra en un ring",
        "El pádel es una variante del tenis en pista cerrada",
        "La esgrima usa espadas en competiciones rápidas",
        "El tiro con arco requiere precisión y enfoque",
        "El triatlón combina natación, ciclismo y carrera",
        "La halterofilia implica levantar pesas",
        "El rugby se juega en dos tiempos con varios jugadores",
        "La escalada se realiza en rocas o paredes artificiales",
        "El patinaje sobre hielo se practica en pistas congeladas",
        "El softball es una variante del béisbol con un balón más grande",
        "El remo se realiza en embarcaciones sobre el agua",
        "La danza es tanto una forma de expresión como un deporte",
        "La vela utiliza el viento para navegar",
        "El senderismo se practica en senderos naturales",
        "El parkour consiste en superar obstáculos urbanos",
        "El kitesurf usa una cometa para impulsarse sobre el agua",
        "El curling se juega sobre hielo con piedras",
        "El tiro deportivo incluye diferentes disciplinas de precisión",
        "El ciclismo de montaña se realiza en terrenos accidentados",
        "La lucha libre profesional es un espectáculo de entretenimiento",
        "El waterpolo se juega en una piscina con balón",
        "El skateboarding se practica en rampas y calles",
        "El tiro al plato es un deporte de precisión con escopeta",
        "El bádminton se juega con un volante y una raqueta",
        "El esquí acuático se realiza en lagos o ríos",
        "La gimnasia rítmica combina elementos de danza y acrobacia",
        "El patinaje artístico en línea se realiza con patines sobre ruedas",
        "El ultimate frisbee se juega con un disco volador",
        "El crossfit es una forma de entrenamiento físico intenso",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El balonmano se juega con un balón en una cancha",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",
        "El levantamiento de pesas incluye diversas técnicas de fuerza",

    ],
    'category': [
         'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
         'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
         'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
         'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
         'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
         'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',

        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',

        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',

        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes'

        ]
}









'''
'category': [
        'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal', 'animal',
        'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía', 'economía','economía', 'economía', 'economía',
        'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología', 'tecnología',
        'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes', 'deportes'
    ]
'''
